server:
  host: "0.0.0.0"
  port: 8080

database:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "subscriptions"
  sslmode: "disable"

logger:
  level: "info"
  encoding: "json"