server:
  host: "0.0.0.0"
  port: 8080

database:
  host: "localhost"
  port: 5432
  user: "admin"
  password: "13371337"
  dbname: "subscriptions"
  sslmode: "disable"

logger:
  level: "info"
  encoding: "json"