// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const calculateTotalCost = `-- name: CalculateTotalCost :one
WITH date_range AS (
    SELECT 
        generate_series($1::DATE, $2::DATE, '1 month'::interval)::DATE AS month_start
),
subscription_costs AS (
    SELECT 
        s.id as subscription_id,
        s.price,
        COUNT(DISTINCT dr.month_start) as months_count
    FROM subscriptions s
    CROSS JOIN date_range dr
    WHERE 
        ($3::UUID IS NULL OR s.user_id = $3) AND
        ($4::VARCHAR IS NULL OR s.service_name ILIKE '%' || $4 || '%') AND
        (s.start_date <= dr.month_start) AND
        (s.end_date IS NULL OR s.end_date >= dr.month_start)
    GROUP BY s.id, s.price
)
SELECT COALESCE(SUM(price * months_count), 0)::BIGINT as total_cost
FROM subscription_costs
`

type CalculateTotalCostParams struct {
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	UserID      pgtype.UUID
	ServiceName pgtype.Text
}

func (q *Queries) CalculateTotalCost(ctx context.Context, arg CalculateTotalCostParams) (int64, error) {
	row := q.db.QueryRow(ctx, calculateTotalCost,
		arg.StartDate,
		arg.EndDate,
		arg.UserID,
		arg.ServiceName,
	)
	var total_cost int64
	err := row.Scan(&total_cost)
	return total_cost, err
}

const countSubscriptions = `-- name: CountSubscriptions :one
SELECT COUNT(*) FROM subscriptions
WHERE 
    ($1::UUID IS NULL OR user_id = $1) AND
    ($2::VARCHAR IS NULL OR service_name ILIKE '%' || $2 || '%')
`

type CountSubscriptionsParams struct {
	UserID      pgtype.UUID
	ServiceName pgtype.Text
}

func (q *Queries) CountSubscriptions(ctx context.Context, arg CountSubscriptionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSubscriptions, arg.UserID, arg.ServiceName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (service_name, price, user_id, start_date, end_date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, service_name, price, user_id, start_date, end_date, created_at, updated_at
`

type CreateSubscriptionParams struct {
	ServiceName string
	Price       int32
	UserID      pgtype.UUID
	StartDate   pgtype.Date
	EndDate     pgtype.Date
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ServiceName,
		arg.Price,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :execrows
DELETE FROM subscriptions WHERE id = $1
`

func (q *Queries) DeleteSubscription(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSubscription, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, service_name, price, user_id, start_date, end_date, created_at, updated_at FROM subscriptions WHERE id = $1
`

func (q *Queries) GetSubscription(ctx context.Context, id pgtype.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, service_name, price, user_id, start_date, end_date, created_at, updated_at FROM subscriptions
WHERE 
    ($1::UUID IS NULL OR user_id = $1) AND
    ($2::VARCHAR IS NULL OR service_name ILIKE '%' || $2 || '%')
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListSubscriptionsParams struct {
	UserID      pgtype.UUID
	ServiceName pgtype.Text
	Offset      int32
	Limit       int32
}

func (q *Queries) ListSubscriptions(ctx context.Context, arg ListSubscriptionsParams) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptions,
		arg.UserID,
		arg.ServiceName,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.ServiceName,
			&i.Price,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE subscriptions 
SET 
    service_name = COALESCE($2, service_name),
    price = COALESCE($3, price),
    start_date = COALESCE($4, start_date),
    end_date = COALESCE($5, end_date),
    updated_at = NOW()
WHERE id = $1
RETURNING id, service_name, price, user_id, start_date, end_date, created_at, updated_at
`

type UpdateSubscriptionParams struct {
	ID          pgtype.UUID
	ServiceName string
	Price       int32
	StartDate   pgtype.Date
	EndDate     pgtype.Date
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscription,
		arg.ID,
		arg.ServiceName,
		arg.Price,
		arg.StartDate,
		arg.EndDate,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
